// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwEnObu_1pOgOW0IYG4vV7gbuCS5y35VI',
    appId: '1:1097911543042:web:a9f86c82ab1c4749710e1b',
    messagingSenderId: '1097911543042',
    projectId: 'panchakarma-991c8',
    authDomain: 'panchakarma-991c8.firebaseapp.com',
    storageBucket: 'panchakarma-991c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2p0QHgl2MeedhW763FRzSJiXNgOL7o0c',
    appId: '1:1097911543042:android:6d6cbd22f845e0de710e1b',
    messagingSenderId: '1097911543042',
    projectId: 'panchakarma-991c8',
    storageBucket: 'panchakarma-991c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGs6t4-aWHERi_WdWAa6jClg-W8UalpFQ',
    appId: '1:1097911543042:ios:f967732eec858f4c710e1b',
    messagingSenderId: '1097911543042',
    projectId: 'panchakarma-991c8',
    storageBucket: 'panchakarma-991c8.firebasestorage.app',
    iosBundleId: 'com.example.panchakarma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGs6t4-aWHERi_WdWAa6jClg-W8UalpFQ',
    appId: '1:1097911543042:ios:f967732eec858f4c710e1b',
    messagingSenderId: '1097911543042',
    projectId: 'panchakarma-991c8',
    storageBucket: 'panchakarma-991c8.firebasestorage.app',
    iosBundleId: 'com.example.panchakarma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwEnObu_1pOgOW0IYG4vV7gbuCS5y35VI',
    appId: '1:1097911543042:web:d026b631e7188e7d710e1b',
    messagingSenderId: '1097911543042',
    projectId: 'panchakarma-991c8',
    authDomain: 'panchakarma-991c8.firebaseapp.com',
    storageBucket: 'panchakarma-991c8.firebasestorage.app',
  );
}
